apiVersion: v1
kind: Service
metadata:
  name: my-app
  annotations:
    nginx-operator.io/hostname: app.example.com
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app
