apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-operator
  template:
    metadata:
      labels:
        app: nginx-operator
    spec:
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: NGINX_REMOTE_HOST
              value: "{{ .Values.nginxServer.host }}"
            - name: NGINX_REMOTE_USER
              value: "{{ .Values.nginxServer.sshUser }}"
            - name: CERT_EMAIL
              value: "{{ .Values.tls.email }}"
            - name: STAGING
              value: "{{ .Values.tls.staging | quote }}"