apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
  annotations:
    nginx.fqdn: demo.example.com
    nginx.nodePort: "30080"
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
