apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-operator
  template:
    metadata:
      labels:
        app: nginx-operator
    spec:
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AWS_REGION
          value: "{{ .Values.aws.region }}"
        - name: HOSTED_ZONE_ID
          value: "{{ .Values.aws.hostedZoneId }}"
        - name: NGINX_HOST
          value: "{{ .Values.nginx.host }}"
        - name: NGINX_USER
          value: "{{ .Values.nginx.user }}"
        - name: NGINX_PUBLIC_IP
          value: "{{ .Values.nginx.publicIp }}"
        - name: NGINX_SSH_KEY_PATH
          value: "/etc/ssh-key/nginx.key"
        volumeMounts:
        - name: ssh-key
          mountPath: /etc/ssh-key
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: {{ .Values.nginx.sshKeySecret }}
