apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
stringData:
  credentials: |
    [default]
    aws_access_key_id = YOUR_ACCESS_KEY
    aws_secret_access_key = YOUR_SECRET_KEY
    region = us-east-1

---

apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssh-key
type: Opaque
stringData:
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...your ssh key...
    -----END OPENSSH PRIVATE KEY-----
